// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking.Data;

#nullable disable

namespace Parking.Migrations
{
    [DbContext(typeof(ParkingContext))]
    partial class ParkingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Parking.Models.PriceTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndSurveillance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalHourlyRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ItialHourlyRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("StartSurveillance")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("PriceTables");
                });

            modelBuilder.Entity("Parking.Models.VehicleRegistration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AmountCharged")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Enter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Exit")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("VehicleRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
